# Generated by Django 3.0.8 on 2021-05-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='props',
            options={'managed': True},
        ),
    ]
