# Generated by Django 3.0.8 on 2021-05-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
