# Generated by Django 3.2 on 2021-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_auto_20211108_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='dataset',
            field=models.TextField(db_column='dataset', default='missing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='props',
            name='species',
            field=models.TextField(blank=True, db_column='species', null=True),
        ),
    ]
