# Generated by Django 3.2 on 2021-11-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0009_auto_20211108_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='props',
            name='Name',
            field=models.TextField(blank=True, db_column='Name', null=True),
        ),
    ]
