# Generated by Django 3.2 on 2021-11-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_auto_20211109_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='props',
            old_name='id',
            new_name='_id',
        ),
    ]
