# Generated by Django 3.2 on 2021-11-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0014_alter_props_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='props',
            name='id',
            field=models.BigIntegerField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
